apiVersion: v1
kind: Service
metadata:
  name: web-todo-svc
  labels:
    name: web-todo-svc
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: web-todo-pod
