name: Deploy to AKS Cluster
on:
  pull_request:
    branches:
    - main
    - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v2
      with:
        login-server: acrstablemint.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t acrstablemint.azurecr.io/web-todo:${{ github.sha }}
        docker push acrstablemint.azurecr.io/web-todo:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v2
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aks-cluster-01
        resource-group: rg-aks-cluster
        
    - uses: Azure/k8s-create-secret@v4
      with:
        container-registry-url: acrstablemint.azurecr.io
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          deployment.yaml
          service.yaml
        images: |
          acrstablemint.azurecr.io/web-todo:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret
